### ISSUE TITLE
.bval/.bvec files?

### ISSUE THREAD

**Issue by ntustison** [stnava/ANTsPyMM#16]
Sorry, @sntava, but I ran into another issue.  What do you recommend with .bval/.bvec files?

```
Checking filename:  /Users/ntustison/Data/Stone/LIMBIC/NRG/ANTsLIMBIC//sub08C105120Yr/ses-1/DTI-LR/000/ANTsLIMBIC_sub08C105120Yr_ses-1_DTI-LR_000.bval
Invalid extension
Traceback (most recent call last):
  File "/Users/ntustison/Data/Stone/LIMBIC/Scripts/convert_to_nrg.py", line 50, in <module>
    subject_directory_bids_to_nrg_conversion(input_directory, output_directory)
  File "/Users/ntustison/Data/Stone/LIMBIC/Scripts/convert_to_nrg.py", line 43, in subject_directory_bids_to_nrg_conversion
    raise ValueError(message)        
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid file extension: Invalid extension. Expected 'nii.gz' or 'json'.
```

**Comment by stnava** [comment]
that's a good point - I will add those as "acceptable" extensions

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPyMM/commit/c9e4ddf6a0ecf104bff30be458e5b29d56b92ddd should be ok now

**Comment by ntustison** [comment]
Perfect.  Tahnks.
